# Generated by Django 5.0.3 on 2024-04-24 19:25

import module.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0003_alter_category_logo_article'),
        ('module', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Block',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('block_visual', models.CharField(choices=module.models.visual_options, max_length=50)),
                ('block_position', models.CharField(max_length=50)),
                ('block_row', models.PositiveIntegerField()),
                ('title', models.CharField(max_length=250)),
                ('show_title', models.BooleanField(default=False)),
                ('articles', models.ManyToManyField(blank=True, to='content.article')),
            ],
        ),
    ]
